clc;
clear;
close;

%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/li/work-folder/kthjocn/revision/revision_4/traffic-distribution-fix-std.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/12/10 21:36:38

%% Initialize variables.
filename = '/home/li/work-folder/kthjocn/revision/revision_4/traffic-distribution-fix-std.csv';
delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
trafficdistributionfixstd = [dataArray{1:end-1}];
%% Clear temporary variables
x = trafficdistributionfixstd;
clearvars filename delimiter startRow formatSpec fileID dataArray ans trafficdistributionfixstd;

%%
for i = 2:2:8
    x(:, i) = cumsum(x(:, i));
end

figure;
hold on;
plot(x(:, 1), x(:, 2))
plot(x(:, 3), x(:, 4))
plot(x(:, 5), x(:, 6))
plot(x(:, 7), x(:, 8))

%%
csvwrite('fix-std-cdf.csv', x);